spring.application.name=demo

# Mude para qualquer porta livre (ex: 8081, 8082, 0 para aleatória)
server.port=8081

# Banco H2 em memï¿½ria
spring.datasource.url=jdbc:h2:mem:diacono
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=teste

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Console H2 (pra debug)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- Configuraï¿½ï¿½es do RabbitMQ (Customizadas) ---
mq.queue.evento=diacono.evento.queue
mq.exchange.evento=diacono.evento.exchange
mq.routing-key.evento=diacono.evento.rk

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# --- Configuraï¿½ï¿½es do Google Auth ---
# Obtenha estas credenciais no Google Cloud Console
client.id.google= 
client.secret.google= 
